package contenttype

import (
	"strings"
	"unicode"
)

// List of ISO 639 set 1 language codes
var languageSet1 = map[string]string{
	"aa": "aar",
	"ab": "abk",
	"ae": "ave",
	"af": "afr",
	"ak": "aka",
	"am": "amh",
	"an": "arg",
	"ar": "ara",
	"as": "asm",
	"av": "ava",
	"ay": "aym",
	"az": "aze",
	"ba": "bak",
	"be": "bel",
	"bg": "bul",
	"bh": "bih",
	"bi": "bis",
	"bm": "bam",
	"bn": "ben",
	"bo": "bod",
	"br": "bre",
	"bs": "bos",
	"ca": "cat",
	"ce": "che",
	"ch": "cha",
	"co": "cos",
	"cr": "cre",
	"cs": "ces",
	"cu": "chu",
	"cv": "chv",
	"cy": "cym",
	"da": "dan",
	"de": "deu",
	"dv": "div",
	"dz": "dzo",
	"ee": "ewe",
	"el": "ell",
	"en": "eng",
	"eo": "epo",
	"es": "spa",
	"et": "est",
	"eu": "eus",
	"fa": "fas",
	"ff": "ful",
	"fi": "fin",
	"fj": "fij",
	"fo": "fao",
	"fr": "fra",
	"fy": "fry",
	"ga": "gle",
	"gd": "gla",
	"gl": "glg",
	"gn": "grn",
	"gu": "guj",
	"gv": "glv",
	"ha": "hau",
	"he": "heb",
	"hi": "hin",
	"ho": "hmo",
	"hr": "hrv",
	"ht": "hat",
	"hu": "hun",
	"hy": "hye",
	"hz": "her",
	"ia": "ina",
	"id": "ind",
	"ie": "ile",
	"ig": "ibo",
	"ii": "iii",
	"ik": "ipk",
	"io": "ido",
	"is": "isl",
	"it": "ita",
	"iu": "iku",
	"ja": "jpn",
	"jv": "jav",
	"ka": "kat",
	"kg": "kon",
	"ki": "kik",
	"kj": "kua",
	"kk": "kaz",
	"kl": "kal",
	"km": "khm",
	"kn": "kan",
	"ko": "kor",
	"kr": "kau",
	"ks": "kas",
	"ku": "kur",
	"kv": "kom",
	"kw": "cor",
	"ky": "kir",
	"la": "lat",
	"lb": "ltz",
	"lg": "lug",
	"li": "lim",
	"ln": "lin",
	"lo": "lao",
	"lt": "lit",
	"lu": "lub",
	"lv": "lav",
	"mg": "mlg",
	"mh": "mah",
	"mi": "mri",
	"mk": "mkd",
	"ml": "mal",
	"mn": "mon",
	"mr": "mar",
	"ms": "msa",
	"mt": "mlt",
	"my": "mya",
	"na": "nau",
	"nb": "nob",
	"nd": "nde",
	"ne": "nep",
	"ng": "ndo",
	"nl": "nld",
	"nn": "nno",
	"no": "nor",
	"nr": "nbl",
	"nv": "nav",
	"ny": "nya",
	"oc": "oci",
	"oj": "oji",
	"om": "orm",
	"or": "ori",
	"os": "oss",
	"pa": "pan",
	"pi": "pli",
	"pl": "pol",
	"ps": "pus",
	"pt": "por",
	"qu": "que",
	"rm": "roh",
	"rn": "run",
	"ro": "ron",
	"ru": "rus",
	"rw": "kin",
	"sa": "san",
	"sc": "srd",
	"sd": "snd",
	"se": "sme",
	"sg": "sag",
	"si": "sin",
	"sk": "slk",
	"sl": "slv",
	"sm": "smo",
	"sn": "sna",
	"so": "som",
	"sq": "sqi",
	"sr": "srp",
	"ss": "ssw",
	"st": "sot",
	"su": "sun",
	"sv": "swe",
	"sw": "swa",
	"ta": "tam",
	"te": "tel",
	"tg": "tgk",
	"th": "tha",
	"ti": "tir",
	"tk": "tuk",
	"tl": "tgl",
	"tn": "tsn",
	"to": "ton",
	"tr": "tur",
	"ts": "tso",
	"tt": "tat",
	"tw": "twi",
	"ty": "tah",
	"ug": "uig",
	"uk": "ukr",
	"ur": "urd",
	"uz": "uzb",
	"ve": "ven",
	"vi": "vie",
	"vo": "vol",
	"wa": "wln",
	"wo": "wol",
	"xh": "xho",
	"yi": "yid",
	"yo": "yor",
	"za": "zha",
	"zh": "zho",
	"zu": "zul",
}

// List of ISO 639 set 2 language codes
var languageSet2 = map[string]string{
	"aar": "aar",
	"abk": "abk",
	"ace": "ace",
	"ach": "ach",
	"ada": "ada",
	"ady": "ady",
	"afa": "afa",
	"afh": "afh",
	"afr": "afr",
	"ain": "ain",
	"aka": "aka",
	"akk": "akk",
	"alb": "sqi",
	"ale": "ale",
	"alg": "alg",
	"alt": "alt",
	"amh": "amh",
	"ang": "ang",
	"anp": "anp",
	"apa": "apa",
	"ara": "ara",
	"arc": "arc",
	"arg": "arg",
	"arm": "hye",
	"arn": "arn",
	"arp": "arp",
	"art": "art",
	"arw": "arw",
	"asm": "asm",
	"ast": "ast",
	"ath": "ath",
	"aus": "aus",
	"ava": "ava",
	"ave": "ave",
	"awa": "awa",
	"aym": "aym",
	"aze": "aze",
	"bad": "bad",
	"bai": "bai",
	"bak": "bak",
	"bal": "bal",
	"bam": "bam",
	"ban": "ban",
	"baq": "eus",
	"bas": "bas",
	"bat": "bat",
	"bej": "bej",
	"bel": "bel",
	"bem": "bem",
	"ben": "ben",
	"ber": "ber",
	"bho": "bho",
	"bih": "bih",
	"bik": "bik",
	"bin": "bin",
	"bis": "bis",
	"bla": "bla",
	"bnt": "bnt",
	"bod": "bod",
	"bos": "bos",
	"bra": "bra",
	"bre": "bre",
	"btk": "btk",
	"bua": "bua",
	"bug": "bug",
	"bul": "bul",
	"bur": "mya",
	"byn": "byn",
	"cad": "cad",
	"cai": "cai",
	"car": "car",
	"cat": "cat",
	"cau": "cau",
	"ceb": "ceb",
	"cel": "cel",
	"ces": "ces",
	"cha": "cha",
	"chb": "chb",
	"che": "che",
	"chg": "chg",
	"chi": "zho",
	"chk": "chk",
	"chm": "chm",
	"chn": "chn",
	"cho": "cho",
	"chp": "chp",
	"chr": "chr",
	"chu": "chu",
	"chv": "chv",
	"chy": "chy",
	"cmc": "cmc",
	"cop": "cop",
	"cor": "cor",
	"cos": "cos",
	"cpe": "cpe",
	"cpf": "cpf",
	"cpp": "cpp",
	"cre": "cre",
	"crh": "crh",
	"crp": "crp",
	"csb": "csb",
	"cus": "cus",
	"cym": "cym",
	"cze": "ces",
	"dak": "dak",
	"dan": "dan",
	"dar": "dar",
	"day": "day",
	"del": "del",
	"den": "den",
	"deu": "deu",
	"dgr": "dgr",
	"din": "din",
	"div": "div",
	"doi": "doi",
	"dra": "dra",
	"dsb": "dsb",
	"dua": "dua",
	"dum": "dum",
	"dut": "nld",
	"dyu": "dyu",
	"dzo": "dzo",
	"efi": "efi",
	"egy": "egy",
	"eka": "eka",
	"ell": "ell",
	"elx": "elx",
	"eng": "eng",
	"enm": "enm",
	"epo": "epo",
	"est": "est",
	"eus": "eus",
	"ewe": "ewe",
	"ewo": "ewo",
	"fan": "fan",
	"fao": "fao",
	"fas": "fas",
	"fat": "fat",
	"fij": "fij",
	"fil": "fil",
	"fin": "fin",
	"fiu": "fiu",
	"fon": "fon",
	"fra": "fra",
	"fre": "fra",
	"frm": "frm",
	"fro": "fro",
	"frr": "frr",
	"frs": "frs",
	"fry": "fry",
	"ful": "ful",
	"fur": "fur",
	"gaa": "gaa",
	"gay": "gay",
	"gba": "gba",
	"gem": "gem",
	"geo": "kat",
	"ger": "deu",
	"gez": "gez",
	"gil": "gil",
	"gla": "gla",
	"gle": "gle",
	"glg": "glg",
	"glv": "glv",
	"gmh": "gmh",
	"goh": "goh",
	"gon": "gon",
	"gor": "gor",
	"got": "got",
	"grb": "grb",
	"grc": "grc",
	"gre": "ell",
	"grn": "grn",
	"gsw": "gsw",
	"guj": "guj",
	"gwi": "gwi",
	"hai": "hai",
	"hat": "hat",
	"hau": "hau",
	"haw": "haw",
	"heb": "heb",
	"her": "her",
	"hil": "hil",
	"him": "him",
	"hin": "hin",
	"hit": "hit",
	"hmn": "hmn",
	"hmo": "hmo",
	"hrv": "hrv",
	"hsb": "hsb",
	"hun": "hun",
	"hup": "hup",
	"hye": "hye",
	"iba": "iba",
	"ibo": "ibo",
	"ice": "isl",
	"ido": "ido",
	"iii": "iii",
	"ijo": "ijo",
	"iku": "iku",
	"ile": "ile",
	"ilo": "ilo",
	"ina": "ina",
	"inc": "inc",
	"ind": "ind",
	"ine": "ine",
	"inh": "inh",
	"ipk": "ipk",
	"ira": "ira",
	"iro": "iro",
	"isl": "isl",
	"ita": "ita",
	"jav": "jav",
	"jbo": "jbo",
	"jpn": "jpn",
	"jpr": "jpr",
	"jrb": "jrb",
	"kaa": "kaa",
	"kab": "kab",
	"kac": "kac",
	"kal": "kal",
	"kam": "kam",
	"kan": "kan",
	"kar": "kar",
	"kas": "kas",
	"kat": "kat",
	"kau": "kau",
	"kaw": "kaw",
	"kaz": "kaz",
	"kbd": "kbd",
	"kha": "kha",
	"khi": "khi",
	"khm": "khm",
	"kho": "kho",
	"kik": "kik",
	"kin": "kin",
	"kir": "kir",
	"kmb": "kmb",
	"kok": "kok",
	"kom": "kom",
	"kon": "kon",
	"kor": "kor",
	"kos": "kos",
	"kpe": "kpe",
	"krc": "krc",
	"krl": "krl",
	"kro": "kro",
	"kru": "kru",
	"kua": "kua",
	"kum": "kum",
	"kur": "kur",
	"kut": "kut",
	"lad": "lad",
	"lah": "lah",
	"lam": "lam",
	"lao": "lao",
	"lat": "lat",
	"lav": "lav",
	"lez": "lez",
	"lim": "lim",
	"lin": "lin",
	"lit": "lit",
	"lol": "lol",
	"loz": "loz",
	"ltz": "ltz",
	"lua": "lua",
	"lub": "lub",
	"lug": "lug",
	"lui": "lui",
	"lun": "lun",
	"luo": "luo",
	"lus": "lus",
	"mac": "mkd",
	"mad": "mad",
	"mag": "mag",
	"mah": "mah",
	"mai": "mai",
	"mak": "mak",
	"mal": "mal",
	"man": "man",
	"mao": "mri",
	"map": "map",
	"mar": "mar",
	"mas": "mas",
	"may": "msa",
	"mdf": "mdf",
	"mdr": "mdr",
	"men": "men",
	"mga": "mga",
	"mic": "mic",
	"min": "min",
	"mis": "mis",
	"mkd": "mkd",
	"mkh": "mkh",
	"mlg": "mlg",
	"mlt": "mlt",
	"mnc": "mnc",
	"mni": "mni",
	"mno": "mno",
	"moh": "moh",
	"mon": "mon",
	"mos": "mos",
	"mri": "mri",
	"msa": "msa",
	"mul": "mul",
	"mun": "mun",
	"mus": "mus",
	"mwl": "mwl",
	"mwr": "mwr",
	"mya": "mya",
	"myn": "myn",
	"myv": "myv",
	"nah": "nah",
	"nai": "nai",
	"nap": "nap",
	"nau": "nau",
	"nav": "nav",
	"nbl": "nbl",
	"nde": "nde",
	"ndo": "ndo",
	"nds": "nds",
	"nep": "nep",
	"new": "new",
	"nia": "nia",
	"nic": "nic",
	"niu": "niu",
	"nld": "nld",
	"nno": "nno",
	"nob": "nob",
	"nog": "nog",
	"non": "non",
	"nor": "nor",
	"nqo": "nqo",
	"nso": "nso",
	"nub": "nub",
	"nwc": "nwc",
	"nya": "nya",
	"nym": "nym",
	"nyn": "nyn",
	"nyo": "nyo",
	"nzi": "nzi",
	"oci": "oci",
	"oji": "oji",
	"ori": "ori",
	"orm": "orm",
	"osa": "osa",
	"oss": "oss",
	"ota": "ota",
	"oto": "oto",
	"paa": "paa",
	"pag": "pag",
	"pal": "pal",
	"pam": "pam",
	"pan": "pan",
	"pap": "pap",
	"pau": "pau",
	"peo": "peo",
	"per": "fas",
	"phi": "phi",
	"phn": "phn",
	"pli": "pli",
	"pol": "pol",
	"pon": "pon",
	"por": "por",
	"pra": "pra",
	"pro": "pro",
	"pus": "pus",
	"que": "que",
	"raj": "raj",
	"rap": "rap",
	"rar": "rar",
	"roa": "roa",
	"roh": "roh",
	"rom": "rom",
	"ron": "ron",
	"rum": "ron",
	"run": "run",
	"rup": "rup",
	"rus": "rus",
	"sad": "sad",
	"sag": "sag",
	"sah": "sah",
	"sai": "sai",
	"sal": "sal",
	"sam": "sam",
	"san": "san",
	"sas": "sas",
	"sat": "sat",
	"scn": "scn",
	"sco": "sco",
	"sel": "sel",
	"sem": "sem",
	"sga": "sga",
	"sgn": "sgn",
	"shn": "shn",
	"sid": "sid",
	"sin": "sin",
	"sio": "sio",
	"sit": "sit",
	"sla": "sla",
	"slk": "slk",
	"slo": "slk",
	"slv": "slv",
	"sma": "sma",
	"sme": "sme",
	"smi": "smi",
	"smj": "smj",
	"smn": "smn",
	"smo": "smo",
	"sms": "sms",
	"sna": "sna",
	"snd": "snd",
	"snk": "snk",
	"sog": "sog",
	"som": "som",
	"son": "son",
	"sot": "sot",
	"spa": "spa",
	"sqi": "sqi",
	"srd": "srd",
	"srn": "srn",
	"srp": "srp",
	"srr": "srr",
	"ssa": "ssa",
	"ssw": "ssw",
	"suk": "suk",
	"sun": "sun",
	"sus": "sus",
	"sux": "sux",
	"swa": "swa",
	"swe": "swe",
	"syc": "syc",
	"syr": "syr",
	"tah": "tah",
	"tai": "tai",
	"tam": "tam",
	"tat": "tat",
	"tel": "tel",
	"tem": "tem",
	"ter": "ter",
	"tet": "tet",
	"tgk": "tgk",
	"tgl": "tgl",
	"tha": "tha",
	"tib": "bod",
	"tig": "tig",
	"tir": "tir",
	"tiv": "tiv",
	"tkl": "tkl",
	"tlh": "tlh",
	"tli": "tli",
	"tmh": "tmh",
	"tog": "tog",
	"ton": "ton",
	"tpi": "tpi",
	"tsi": "tsi",
	"tsn": "tsn",
	"tso": "tso",
	"tuk": "tuk",
	"tum": "tum",
	"tup": "tup",
	"tur": "tur",
	"tut": "tut",
	"tvl": "tvl",
	"twi": "twi",
	"tyv": "tyv",
	"udm": "udm",
	"uga": "uga",
	"uig": "uig",
	"ukr": "ukr",
	"umb": "umb",
	"und": "und",
	"urd": "urd",
	"uzb": "uzb",
	"vai": "vai",
	"ven": "ven",
	"vie": "vie",
	"vol": "vol",
	"vot": "vot",
	"wak": "wak",
	"wal": "wal",
	"war": "war",
	"was": "was",
	"wel": "cym",
	"wen": "wen",
	"wln": "wln",
	"wol": "wol",
	"xal": "xal",
	"xho": "xho",
	"yao": "yao",
	"yap": "yap",
	"yid": "yid",
	"yor": "yor",
	"ypk": "ypk",
	"zap": "zap",
	"zbl": "zbl",
	"zen": "zen",
	"zgh": "zgh",
	"zha": "zha",
	"zho": "zho",
	"znd": "znd",
	"zul": "zul",
	"zun": "zun",
	"zxx": "zxx",
	"zza": "zza",
}

// List of ISO 15924 scripts
var scripts = map[string]string{
	"Adlm": "166",
	"Afak": "439",
	"Aghb": "239",
	"Ahom": "338",
	"Arab": "160",
	"Aran": "161",
	"Armi": "124",
	"Armn": "230",
	"Avst": "134",
	"Bali": "360",
	"Bamu": "435",
	"Bass": "259",
	"Batk": "365",
	"Beng": "325",
	"Berf": "258",
	"Bhks": "334",
	"Blis": "550",
	"Bopo": "285",
	"Brah": "300",
	"Brai": "570",
	"Bugi": "367",
	"Buhd": "372",
	"Cakm": "349",
	"Cans": "440",
	"Cari": "201",
	"Cham": "358",
	"Cher": "445",
	"Chis": "298",
	"Chrs": "109",
	"Cirt": "291",
	"Copt": "204",
	"Cpmn": "402",
	"Cprt": "403",
	"Cyrl": "220",
	"Cyrs": "221",
	"Deva": "315",
	"Diak": "342",
	"Dogr": "328",
	"Dsrt": "250",
	"Dupl": "755",
	"Egyd": "070",
	"Egyh": "060",
	"Egyp": "050",
	"Elba": "226",
	"Elym": "128",
	"Ethi": "430",
	"Gara": "164",
	"Geok": "241",
	"Geor": "240",
	"Glag": "225",
	"Gong": "312",
	"Gonm": "313",
	"Goth": "206",
	"Gran": "343",
	"Grek": "200",
	"Gujr": "320",
	"Gukh": "397",
	"Guru": "310",
	"Hanb": "503",
	"Hang": "286",
	"Hani": "500",
	"Hano": "371",
	"Hans": "501",
	"Hant": "502",
	"Hatr": "127",
	"Hebr": "125",
	"Hira": "410",
	"Hluw": "080",
	"Hmng": "450",
	"Hmnp": "451",
	"Hrkt": "412",
	"Hung": "176",
	"Inds": "610",
	"Ital": "210",
	"Jamo": "284",
	"Java": "361",
	"Jpan": "413",
	"Jurc": "510",
	"Kali": "357",
	"Kana": "411",
	"Kawi": "368",
	"Khar": "305",
	"Khmr": "355",
	"Khoj": "322",
	"Kitl": "505",
	"Kits": "288",
	"Knda": "345",
	"Kore": "287",
	"Kpel": "436",
	"Krai": "396",
	"Kthi": "317",
	"Lana": "351",
	"Laoo": "356",
	"Latf": "217",
	"Latg": "216",
	"Latn": "215",
	"Leke": "364",
	"Lepc": "335",
	"Limb": "336",
	"Lina": "400",
	"Linb": "401",
	"Lisu": "399",
	"Loma": "437",
	"Lyci": "202",
	"Lydi": "116",
	"Mahj": "314",
	"Maka": "366",
	"Mand": "140",
	"Mani": "139",
	"Marc": "332",
	"Maya": "90",
	"Medf": "265",
	"Mend": "438",
	"Merc": "101",
	"Mero": "100",
	"Mlym": "347",
	"Modi": "324",
	"Mong": "145",
	"Moon": "218",
	"Mroo": "264",
	"Mtei": "337",
	"Mult": "323",
	"Mymr": "350",
	"Nagm": "295",
	"Nand": "311",
	"Narb": "106",
	"Nbat": "159",
	"Newa": "333",
	"Nkdb": "085",
	"Nkgb": "420",
	"Nkoo": "165",
	"Nshu": "499",
	"Ogam": "212",
	"Olck": "261",
	"Onao": "296",
	"Orkh": "175",
	"Orya": "327",
	"Osge": "219",
	"Osma": "260",
	"Ougr": "143",
	"Palm": "126",
	"Pauc": "263",
	"Pcun": "015",
	"Pelm": "016",
	"Perm": "227",
	"Phag": "331",
	"Phli": "131",
	"Phlp": "132",
	"Phlv": "133",
	"Phnx": "115",
	"Piqd": "293",
	"Plrd": "282",
	"Prti": "130",
	"Psin": "103",
	"Ranj": "303",
	"Rjng": "363",
	"Rohg": "167",
	"Roro": "620",
	"Runr": "211",
	"Samr": "123",
	"Sara": "292",
	"Sarb": "105",
	"Saur": "344",
	"Sgnw": "095",
	"Shaw": "281",
	"Shrd": "319",
	"Shui": "530",
	"Sidd": "302",
	"Sidt": "180",
	"Sind": "318",
	"Sinh": "348",
	"Sogd": "141",
	"Sogo": "142",
	"Sora": "398",
	"Soyo": "329",
	"Sund": "362",
	"Sunu": "274",
	"Sylo": "316",
	"Syrc": "135",
	"Syre": "138",
	"Syrj": "137",
	"Syrn": "136",
	"Tagb": "373",
	"Takr": "321",
	"Tale": "353",
	"Talu": "354",
	"Taml": "346",
	"Tang": "520",
	"Tavt": "359",
	"Tayo": "380",
	"Telu": "340",
	"Teng": "290",
	"Tfng": "120",
	"Tglg": "370",
	"Thaa": "170",
	"Thai": "352",
	"Tibt": "330",
	"Tirh": "326",
	"Tnsa": "275",
	"Todr": "229",
	"Tols": "299",
	"Toto": "294",
	"Tutg": "341",
	"Ugar": "040",
	"Vaii": "470",
	"Visp": "280",
	"Vith": "228",
	"Wara": "262",
	"Wcho": "283",
	"Wole": "480",
	"Xpeo": "030",
	"Xsux": "020",
	"Yezi": "192",
	"Yiii": "460",
	"Zanb": "339",
	"Zinh": "994",
	"Zmth": "995",
	"Zsye": "993",
	"Zsym": "996",
	"Zxxx": "997",
	"Zyyy": "998",
	"Zzzz": "999",
}

// List of ISO 3166-1 countries
var countryCodes = map[string]string{
	"AD": "020",
	"AE": "784",
	"AF": "004",
	"AG": "028",
	"AI": "660",
	"AL": "008",
	"AM": "051",
	"AO": "024",
	"AQ": "010",
	"AR": "032",
	"AS": "016",
	"AT": "040",
	"AU": "036",
	"AW": "533",
	"AX": "248",
	"AZ": "031",
	"BA": "070",
	"BB": "052",
	"BD": "050",
	"BE": "056",
	"BF": "854",
	"BG": "100",
	"BH": "048",
	"BI": "108",
	"BJ": "204",
	"BL": "652",
	"BM": "060",
	"BN": "096",
	"BO": "068",
	"BQ": "535",
	"BR": "076",
	"BS": "044",
	"BT": "064",
	"BV": "074",
	"BW": "072",
	"BY": "112",
	"BZ": "084",
	"CA": "124",
	"CC": "166",
	"CD": "180",
	"CF": "140",
	"CG": "178",
	"CH": "756",
	"CI": "384",
	"CK": "184",
	"CL": "152",
	"CM": "120",
	"CN": "156",
	"CO": "170",
	"CR": "188",
	"CU": "192",
	"CV": "132",
	"CW": "531",
	"CX": "162",
	"CY": "196",
	"CZ": "203",
	"DE": "276",
	"DJ": "262",
	"DK": "208",
	"DM": "212",
	"DO": "214",
	"DZ": "012",
	"EC": "218",
	"EE": "233",
	"EG": "818",
	"EH": "732",
	"ER": "232",
	"ES": "724",
	"ET": "231",
	"FI": "246",
	"FJ": "242",
	"FK": "238",
	"FM": "583",
	"FO": "234",
	"FR": "250",
	"GA": "266",
	"GB": "826",
	"GD": "308",
	"GE": "268",
	"GF": "254",
	"GG": "831",
	"GH": "288",
	"GI": "292",
	"GL": "304",
	"GM": "270",
	"GN": "324",
	"GP": "312",
	"GQ": "226",
	"GR": "300",
	"GS": "239",
	"GT": "320",
	"GU": "316",
	"GW": "624",
	"GY": "328",
	"HK": "344",
	"HM": "334",
	"HN": "340",
	"HR": "191",
	"HT": "332",
	"HU": "348",
	"ID": "360",
	"IE": "372",
	"IL": "376",
	"IM": "833",
	"IN": "356",
	"IO": "086",
	"IQ": "368",
	"IR": "364",
	"IS": "352",
	"IT": "380",
	"JE": "832",
	"JM": "388",
	"JO": "400",
	"JP": "392",
	"KE": "404",
	"KG": "417",
	"KH": "116",
	"KI": "296",
	"KM": "174",
	"KN": "659",
	"KP": "408",
	"KR": "410",
	"KW": "414",
	"KY": "136",
	"KZ": "398",
	"LA": "418",
	"LB": "422",
	"LC": "662",
	"LI": "438",
	"LK": "144",
	"LR": "430",
	"LS": "426",
	"LT": "440",
	"LU": "442",
	"LV": "428",
	"LY": "434",
	"MA": "504",
	"MC": "492",
	"MD": "498",
	"ME": "499",
	"MF": "663",
	"MG": "450",
	"MH": "584",
	"MK": "807",
	"ML": "466",
	"MM": "104",
	"MN": "496",
	"MO": "446",
	"MP": "580",
	"MQ": "474",
	"MR": "478",
	"MS": "500",
	"MT": "470",
	"MU": "480",
	"MV": "462",
	"MW": "454",
	"MX": "484",
	"MY": "458",
	"MZ": "508",
	"NA": "516",
	"NC": "540",
	"NE": "562",
	"NF": "574",
	"NG": "566",
	"NI": "558",
	"NL": "528",
	"NO": "578",
	"NP": "524",
	"NR": "520",
	"NU": "570",
	"NZ": "554",
	"OM": "512",
	"PA": "591",
	"PE": "604",
	"PF": "258",
	"PG": "598",
	"PH": "608",
	"PK": "586",
	"PL": "616",
	"PM": "666",
	"PN": "612",
	"PR": "630",
	"PS": "275",
	"PT": "620",
	"PW": "585",
	"PY": "600",
	"QA": "634",
	"RE": "638",
	"RO": "642",
	"RS": "688",
	"RU": "643",
	"RW": "646",
	"SA": "682",
	"SB": "090",
	"SC": "690",
	"SD": "729",
	"SE": "752",
	"SG": "702",
	"SH": "654",
	"SI": "705",
	"SJ": "744",
	"SK": "703",
	"SL": "694",
	"SM": "674",
	"SN": "686",
	"SO": "706",
	"SR": "740",
	"SS": "728",
	"ST": "678",
	"SV": "222",
	"SX": "534",
	"SY": "760",
	"SZ": "748",
	"TC": "796",
	"TD": "148",
	"TF": "260",
	"TG": "768",
	"TH": "764",
	"TJ": "762",
	"TK": "772",
	"TL": "626",
	"TM": "795",
	"TN": "788",
	"TO": "776",
	"TR": "792",
	"TT": "780",
	"TV": "798",
	"TW": "158",
	"TZ": "834",
	"UA": "804",
	"UG": "800",
	"UM": "581",
	"US": "840",
	"UY": "858",
	"UZ": "860",
	"VA": "336",
	"VC": "670",
	"VE": "862",
	"VG": "092",
	"VI": "850",
	"VN": "704",
	"VU": "548",
	"WF": "876",
	"WS": "882",
	"YE": "887",
	"YT": "175",
	"ZA": "710",
	"ZM": "894",
	"ZW": "716",
}

// List of ISO 3166-1 countries
var countryNumbers = map[string]string{
	"004": "AF",
	"008": "AL",
	"010": "AQ",
	"012": "DZ",
	"016": "AS",
	"020": "AD",
	"024": "AO",
	"028": "AG",
	"031": "AZ",
	"032": "AR",
	"036": "AU",
	"040": "AT",
	"044": "BS",
	"048": "BH",
	"050": "BD",
	"051": "AM",
	"052": "BB",
	"056": "BE",
	"060": "BM",
	"064": "BT",
	"068": "BO",
	"070": "BA",
	"072": "BW",
	"074": "BV",
	"076": "BR",
	"084": "BZ",
	"086": "IO",
	"090": "SB",
	"092": "VG",
	"096": "BN",
	"100": "BG",
	"104": "MM",
	"108": "BI",
	"112": "BY",
	"116": "KH",
	"120": "CM",
	"124": "CA",
	"132": "CV",
	"136": "KY",
	"140": "CF",
	"144": "LK",
	"148": "TD",
	"152": "CL",
	"156": "CN",
	"158": "TW",
	"162": "CX",
	"166": "CC",
	"170": "CO",
	"174": "KM",
	"175": "YT",
	"178": "CG",
	"180": "CD",
	"184": "CK",
	"188": "CR",
	"191": "HR",
	"192": "CU",
	"196": "CY",
	"203": "CZ",
	"204": "BJ",
	"208": "DK",
	"212": "DM",
	"214": "DO",
	"218": "EC",
	"222": "SV",
	"226": "GQ",
	"231": "ET",
	"232": "ER",
	"233": "EE",
	"234": "FO",
	"238": "FK",
	"239": "GS",
	"242": "FJ",
	"246": "FI",
	"248": "AX",
	"250": "FR",
	"254": "GF",
	"258": "PF",
	"260": "TF",
	"262": "DJ",
	"266": "GA",
	"268": "GE",
	"270": "GM",
	"275": "PS",
	"276": "DE",
	"288": "GH",
	"292": "GI",
	"296": "KI",
	"300": "GR",
	"304": "GL",
	"308": "GD",
	"312": "GP",
	"316": "GU",
	"320": "GT",
	"324": "GN",
	"328": "GY",
	"332": "HT",
	"334": "HM",
	"336": "VA",
	"340": "HN",
	"344": "HK",
	"348": "HU",
	"352": "IS",
	"356": "IN",
	"360": "ID",
	"364": "IR",
	"368": "IQ",
	"372": "IE",
	"376": "IL",
	"380": "IT",
	"384": "CI",
	"388": "JM",
	"392": "JP",
	"398": "KZ",
	"400": "JO",
	"404": "KE",
	"408": "KP",
	"410": "KR",
	"414": "KW",
	"417": "KG",
	"418": "LA",
	"422": "LB",
	"426": "LS",
	"428": "LV",
	"430": "LR",
	"434": "LY",
	"438": "LI",
	"440": "LT",
	"442": "LU",
	"446": "MO",
	"450": "MG",
	"454": "MW",
	"458": "MY",
	"462": "MV",
	"466": "ML",
	"470": "MT",
	"474": "MQ",
	"478": "MR",
	"480": "MU",
	"484": "MX",
	"492": "MC",
	"496": "MN",
	"498": "MD",
	"499": "ME",
	"500": "MS",
	"504": "MA",
	"508": "MZ",
	"512": "OM",
	"516": "NA",
	"520": "NR",
	"524": "NP",
	"528": "NL",
	"531": "CW",
	"533": "AW",
	"534": "SX",
	"535": "BQ",
	"540": "NC",
	"548": "VU",
	"554": "NZ",
	"558": "NI",
	"562": "NE",
	"566": "NG",
	"570": "NU",
	"574": "NF",
	"578": "NO",
	"580": "MP",
	"581": "UM",
	"583": "FM",
	"584": "MH",
	"585": "PW",
	"586": "PK",
	"591": "PA",
	"598": "PG",
	"600": "PY",
	"604": "PE",
	"608": "PH",
	"612": "PN",
	"616": "PL",
	"620": "PT",
	"624": "GW",
	"626": "TL",
	"630": "PR",
	"634": "QA",
	"638": "RE",
	"642": "RO",
	"643": "RU",
	"646": "RW",
	"652": "BL",
	"654": "SH",
	"659": "KN",
	"660": "AI",
	"662": "LC",
	"663": "MF",
	"666": "PM",
	"670": "VC",
	"674": "SM",
	"678": "ST",
	"682": "SA",
	"686": "SN",
	"688": "RS",
	"690": "SC",
	"694": "SL",
	"702": "SG",
	"703": "SK",
	"704": "VN",
	"705": "SI",
	"706": "SO",
	"710": "ZA",
	"716": "ZW",
	"724": "ES",
	"728": "SS",
	"729": "SD",
	"732": "EH",
	"740": "SR",
	"744": "SJ",
	"748": "SZ",
	"752": "SE",
	"756": "CH",
	"760": "SY",
	"762": "TJ",
	"764": "TH",
	"768": "TG",
	"772": "TK",
	"776": "TO",
	"780": "TT",
	"784": "AE",
	"788": "TN",
	"792": "TR",
	"795": "TM",
	"796": "TC",
	"798": "TV",
	"800": "UG",
	"804": "UA",
	"807": "MK",
	"818": "EG",
	"826": "GB",
	"831": "GG",
	"832": "JE",
	"833": "IM",
	"834": "TZ",
	"840": "US",
	"850": "VI",
	"854": "BF",
	"858": "UY",
	"860": "UZ",
	"862": "VE",
	"876": "WF",
	"882": "WS",
	"887": "YE",
	"894": "ZM",
}

type Language struct {
	Language string
	Script   string
	Region   string
	Variant  string
}

// NewLanguage parses the string and returns an instance of Language struct.
func NewLanguage(s string) Language {
	language, err := ParseLanguage(s)
	if err != nil {
		return Language{}
	}

	return language
}

// ParseLanguage parses the given string as a language and returns it as a Language.
// If the string cannot be parsed an appropriate error is returned.
func ParseLanguage(s string) (Language, error) {
	// RFC 4647, 2.1 Basic Language Range
	language := Language{}
	var consumed bool
	if language.Language, language.Script, language.Region, language.Variant, s, consumed = consumeLanguageTags(skipWhitespaces(s)); !consumed {
		return Language{}, ErrInvalidLanguage
	}

	// there must not be anything left after parsing the header
	if len(s) > 0 {
		return Language{}, ErrInvalidMediaType
	}

	return language, nil
}

func consumeLanguageTag(s string) (language, remaining string, consumed bool) {
	// RFC 5646, 2.1. Syntax
	for i := 0; i < len(s); i++ {
		if !isAlphaChar(s[i]) {
			if len(s) >= 2 {
				return strings.ToLower(s[:i]), s[i:], true
			} else {
				return "", s, false
			}
		}
	}

	return strings.ToLower(s), "", len(s) >= 2
}

func consumeTag(s string) (language, remaining string, consumed bool) {
	// RFC 5646, 2.1. Syntax
	for i := 0; i < len(s); i++ {
		if !isAlphaChar(s[i]) && !isDigitChar(s[i]) {
			if len(s) >= 2 {
				return s[:i], s[i:], true
			} else {
				return "", s, false
			}
		}
	}

	return strings.ToLower(s), "", len(s) >= 2
}

func isValidLanguage(language string) bool {
	if len(language) == 2 {
		_, ok := languageSet1[strings.ToLower(language)]
		return ok
	} else if len(language) == 3 {
		_, ok := languageSet2[strings.ToLower(language)]
		return ok
	}

	return false
}

// Capitalize the first letter and make the rest lowercase
func capitalize(s string) string {
	if len(s) == 0 {
		return s
	}
	runes := []rune(s)
	runes[0] = unicode.ToUpper(runes[0])
	return string(runes[0]) + strings.ToLower(string(runes[1:]))
}

func isValidScript(script string) bool {
	if len(script) == 4 {
		_, ok := scripts[capitalize(script)]
		return ok
	}

	return false
}

func isValidCountry(country string) bool {
	if len(country) == 2 {
		_, ok := countryCodes[strings.ToUpper(country)]
		return ok
	} else if len(country) == 3 {
		_, ok := countryNumbers[strings.ToUpper(country)]
		return ok
	}

	return false
}

func isValidVariant(variant string) bool {
	// RFC 5646, 2.1. Syntax
	if len(variant) >= 5 && len(variant) <= 8 {
		for i := 0; i < len(variant); i++ {
			if !isAlphaChar(variant[i]) && !isDigitChar(variant[i]) {
				return false
			}
		}
		return true
	} else if len(variant) == 4 {
		if !isDigitChar(variant[0]) {
			return false
		}
		for i := 1; i < len(variant); i++ {
			if !isAlphaChar(variant[i]) && !isDigitChar(variant[i]) {
				return false
			}
		}
		return true
	}

	return false
}

func consumeLanguageTags(s string) (language, script, region, variant, remaining string, consumed bool) {
	// RFC 5646, 2.1. Syntax
	language, remaining, consumed = consumeLanguageTag(s)

	if !consumed {
		return "", "", "", "", s, false
	}

	if !isValidLanguage(language) {
		return "", "", "", "", s, false
	}

	for i := 0; i < 4; {
		var skipped bool
		remaining, skipped = skipCharacter(remaining, '-')
		if !skipped {
			if len(remaining) == 0 {
				return language, script, region, variant, remaining, true
			} else {
				return "", "", "", "", s, false
			}
		}

		var tag string
		tag, remaining, consumed = consumeTag(remaining)

		if !consumed {
			return "", "", "", "", s, false
		}

		if i == 0 && isValidScript(tag) {
			script = capitalize(tag)
			i = 1
		} else if i <= 1 && isValidCountry(tag) {
			region = strings.ToUpper(tag)
			i = 2
		} else if i <= 2 && isValidVariant(tag) {
			variant = strings.ToLower(tag)
			i = 3
		} else {
			return "", "", "", "", s, false
		}
	}

	return language, script, region, remaining, "", true
}
